/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  archived?: boolean;
  author?: string;
  coverUrl?: Array<string>;
  id?: number;
  isbn?: string;
  owner?: string;
  rating?: number;
  sharable?: boolean;
  synopsis?: string;
  title?: string;
}
