/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterUserRequest {
  dateOfBirth?: string;
  email: string;
  password: string;
  username: string;
}
